### ISSUE TITLE
Issue in card swipe

### ISSUE THREAD

**Issue by ankushsdei** [CardFlight/cardflight-android#8]
While further working with the Swiper, we faced very delayed response issue using following steps. 
Can you please help us to resolve this or any particular reason of the issue which we can look into. 
1) Connect the Swiper and it gets connected. 
2) Click on back screen of the app (We are calling Reader.tearDown() ;) . 
3) Again come on swiper screen and it connects the swiper. But this time, it makes 4-5 attempts to connect and due to this, it takes approx. 45 seconds to connect which is very high waiting time. Sometimes, it even shows timeout and didn’t even connect. 
4) We have checked that when we click on Back button, onDestroy function is called each time. 
5) Kindly suggest if need to change or missing anything. Please check the logs file attached in this email. Hope to hear from you soon.

Also please find out the log file as well. There is also one exception logged from your side.
[CompleteLog.txt](https://github.com/CardFlight/cardflight-android/files/121698/CompleteLog.txt)

Best Regards,

**Comment by austinodell** [comment]
Hi Ankush,

What method are you using to connect to the Reader?  It looks like you may be trying to connect to two separate Reader instances at once.  I would highly recommend using `Reader.getDefault(context)` to access your Reader instance to prevent this from happening.

Thanks,
Austin

**Comment by ankushsdei** [comment]
We are using the same as you mentioned Reader.getdefault

**Comment by austinodell** [comment]
Connection times can vary due to a lot of factors, many of which are outside of our control.  It will always depend on what device you are using with what reader.  To ensure the best possible experience, ensure you are not repeatedly calling `Reader.getDefault(context)`, `Reader.tearDown()`, or Reader.destroy`.  Also ensure that the device's volume is at 100%. The SDK will attempt to do this for the user, however some devices (like any Samsung) will warn the user and require they accept a prompt.

A feature you can look for in the next release of the SDK is to specify which reader you wish to connect to at connection time, which will drastically reduce the wait time.

**Comment by rishabhbsdei** [comment]
We understand that we shouldn't be calling Reader.getDefault(context), Reader.tearDown() in repeatedly manner and to avoid this we have tried to initialize the SDK and Reader object in our application launch delegates and setting up the setDeviceHandler in our activity where we are processing the card swipe functionalities. When we intialize the reader and SDK in application launch the second activity view where we need the connection to reader doesnt work as we get the reader in disconnected state. Please guide us to initialize the reader in application launch so that we can use the reader in other activity without the need to reinitialize it. If this works then we will also not need to call tearDown method unless we exit from the app. OR if we can get some assistance in creating the connection again for the Reader object that can also help in solving our requirements.

Also, even if you unplug the device and plug it again it taking same time around 45-50 seconds or more.

Please assist.

Regards
Rishabh

**Comment by austinodell** [comment]
If you would like to initialize the Reader object once and leave it connected, that is definitely an option. In the initial activity, you should call `Reader.getDefault(context)` to initialize the reader, and also assign it's CardFlightDeviceHandler implementation.  From this point on, you can always access the Reader using the same `Reader.getDefault(context)` within each activity.  One issue you may run in to is if you are trying to use the singleton across multiple activities at the same time, which is not allowed.

We are constantly working on improving connection times to the readers.  In our next release, we are including the ability to choose which reader to connect to if you are only using one, or if you want to implement a way to set a default based on the last used reader type.  You can expect this by the end of the month.

Thanks,
Austin

**Comment by ankushsdei** [comment]
We just followed as you mentioned in your response above. In our app launch we initialized the SDK and Reader object with below mentioned code. 
```
CardFlight.getInstance().setApiTokenAndAccountToken(PreferencesHelper.API_TOKEN, PreferencesHelper.ACCOUNT_TOKEN);
CardFlight.getInstance().setLogging(true);
Reader.getDefault(this)

```
In our payments activity we set the device handlers as mentioned below.
```
Reader.getDefault(this)
.setDeviceHandler(this)
.setAutoConfigHandler(this);
```

The above setup of code results in Reader not initialized on our payments activity. In our callbacks on payments activity we only got the disconnected state. Please let us know if are missing anything here in our initialization which we need to take care of.

Regards,
Ankush

**Comment by austinodell** [comment]
I would highly recommend setting the device handler and auto config handler when you first call `Reader.getDefault(context)`.  However, the logic should be working.  Are you sure the device you are using is compatible with the reader you are trying to use?  You can check [here](https://cardflight.com/docs/android) for a compatibility list.

If it is compatible, does the reader connect when you initially call `Reader.getDefault(context)`?

Thanks,
Austin
